// Generated by build_proposal_data.py in the invited-clubs-memberships repo
// (tenant-admin-web/docs/claude-artifacts/clubhouse360-market-matrix/source).
// Do not edit by hand: change the source rows there and run it again.
// Statuses are read from the product's code: Built works end to end;
// Configure is built and needs only an account, key or hardware; Gap is not
// built yet.

export type FeatureStatus = "Built" | "Configure" | "Gap";

export interface Feature {
  id: string;
  name: string;
  status: FeatureStatus;
  /** Uses an AI model. */
  ai: boolean;
  /** Why it matters, or for Configure and Gap, what it still needs. */
  note: string;
}

export interface AppArea {
  key: string;
  name: string;
  blurb: string;
  features: Feature[];
}

export const APPS: AppArea[] = [
  {
    "key": "sales",
    "name": "Sales & Membership",
    "blurb": "Leads, the pipeline, selling a membership, contracts and plan changes.",
    "features": [
      {
        "id": "F01",
        "name": "Lead capture from web forms and file import, lead grades, possible-duplicate detection",
        "status": "Built",
        "ai": false,
        "note": "Leads arrive graded and flagged as possible duplicates, so sales staff never call the same family twice."
      },
      {
        "id": "F02",
        "name": "Sales pipeline (opportunities by stage) with tours, tasks and activity timeline",
        "status": "Built",
        "ai": false,
        "note": ""
      },
      {
        "id": "F03",
        "name": "One-path selling: one dialog builds the whole sale (plan, household, add-ons, fees, joining fee)",
        "status": "Built",
        "ai": false,
        "note": "A whole membership sale, from plan to household to joining fee, is built in one place with discount limits and GM approval built in."
      },
      {
        "id": "F04",
        "name": "E-signature contracts with amendments, and waivers signed in the same ceremony",
        "status": "Built",
        "ai": false,
        "note": "Members sign the agreement and every waiver in one signing session, with no separate e-signature license."
      },
      {
        "id": "F05",
        "name": "Membership plan change (upgrade/downgrade) as a signed amendment with fee difference",
        "status": "Built",
        "ai": false,
        "note": "An upgrade or downgrade is signed as an amendment first and the joining-fee difference is worked out automatically."
      },
      {
        "id": "F07",
        "name": "Online self-serve join (prospect buys a membership online)",
        "status": "Built",
        "ai": false,
        "note": "A prospect can pick a plan, sign and pay to join online without a single phone call."
      },
      {
        "id": "F08",
        "name": "Event/catering instant quote wizard for the public",
        "status": "Built",
        "ai": false,
        "note": "Someone planning a wedding gets a priced quote online in minutes, then accepts, signs and pays the deposit on one page."
      },
      {
        "id": "F09",
        "name": "Next Step: one open next action per record, owner reassignment when staff leave",
        "status": "Built",
        "ai": false,
        "note": "Every record always shows exactly one next step, and when a salesperson leaves, the GM hands their work to someone else so nothing goes cold."
      },
      {
        "id": "X05",
        "name": "Membership applications with credit and background checks",
        "status": "Built",
        "ai": false,
        "note": "Applications move through credit and background checks in one review queue."
      },
      {
        "id": "X27",
        "name": "Never a dead end: when a step needs a missing detail (date of birth, address, phone), the screen asks for it right there and carries on",
        "status": "Built",
        "ai": false,
        "note": "A contract can't go out with a blank in it, and staff never get an error with nowhere to type the fix: the missing field opens in place and the action finishes."
      },
      {
        "id": "F06",
        "name": "Member financing / payment plans with soft credit check",
        "status": "Configure",
        "ai": false,
        "note": "Needs the club's credit bureau account and each club's interest rate."
      },
      {
        "id": "C33",
        "name": "Membership director briefing: who is on property today, preferences, birthdays",
        "status": "Gap",
        "ai": false,
        "note": "Pieces exist separately (check-in roster, a birthdays view, dining likes), but there is no single daily briefing of who is on property with their preferences and birthdays."
      }
    ]
  },
  {
    "key": "marketing",
    "name": "Marketing",
    "blurb": "Journeys, campaigns, email in the club's brand, surveys and the website.",
    "features": [
      {
        "id": "F10",
        "name": "Visual automation/journey builder (triggers, waits, branches)",
        "status": "Built",
        "ai": false,
        "note": "Staff draw member journeys with waits and branches on a canvas, with quiet hours and consent checks handled for them."
      },
      {
        "id": "F11",
        "name": "Email templates editable by team, rendered in each club's brand",
        "status": "Built",
        "ai": false,
        "note": ""
      },
      {
        "id": "F12",
        "name": "Campaigns to email, push and the in-app inbox with merge tokens",
        "status": "Built",
        "ai": false,
        "note": "One campaign reaches members by email, phone alert and the app inbox, each message filled in with their own details."
      },
      {
        "id": "F13",
        "name": "Revenue-from-marketing attribution (touch credit to campaigns)",
        "status": "Built",
        "ai": false,
        "note": "Marketing can show exactly how many dollars each campaign brought in, not just opens and clicks."
      },
      {
        "id": "F14",
        "name": "Surveys sent after visits, results on the record",
        "status": "Built",
        "ai": false,
        "note": "A survey goes out automatically after a round, a dinner or an event, and the score lands on the member's record and the satisfaction report."
      },
      {
        "id": "F15",
        "name": "Club website publishing / CMS",
        "status": "Built",
        "ai": false,
        "note": "Each club edits and publishes its own website pages, forms and photos without a web agency."
      },
      {
        "id": "F16",
        "name": "Email history on every person record",
        "status": "Built",
        "ai": false,
        "note": ""
      },
      {
        "id": "X01",
        "name": "Fundraising and giving: donations, pledges, gift batches, soft credits and recurring gifts",
        "status": "Built",
        "ai": false,
        "note": "A foundation or charity arm can run its giving in the same system as the club."
      },
      {
        "id": "X07",
        "name": "Member Health score and Retention / At Risk lists",
        "status": "Built",
        "ai": false,
        "note": "The club sees which members are drifting away, and why, before they resign."
      },
      {
        "id": "C27",
        "name": "Loyalty points earned on spend, redeemed as payment with time/place rules",
        "status": "Built",
        "ai": false,
        "note": "Members earn points on spend and pay part of a sale with them, with club rules; managers adjust points with a reason; a canceled order gives its points back. Points owed are a liability in the books."
      },
      {
        "id": "C30",
        "name": "Online forms with payments",
        "status": "Built",
        "ai": false,
        "note": "A form can take a payment: staff add charge items to the form, and the payment lands on an invoice like any other."
      },
      {
        "id": "C28",
        "name": "SMS marketing campaigns",
        "status": "Configure",
        "ai": false,
        "note": "Campaigns send by text to opted-in members through the club's own number; it needs the club's texting account connected."
      },
      {
        "id": "IC60",
        "name": "Flyer designer and posting to social media",
        "status": "Gap",
        "ai": false,
        "note": "Not built yet."
      }
    ]
  },
  {
    "key": "service",
    "name": "Member Service",
    "blurb": "Cases, chat, alerts and help, for members and for staff.",
    "features": [
      {
        "id": "F17",
        "name": "Service cases with dashboards and reports",
        "status": "Built",
        "ai": false,
        "note": "A service case can make it right on the spot with a comp or credit within each role's limit."
      },
      {
        "id": "F18",
        "name": "In-app \"Report a Problem\" with a step recorder",
        "status": "Built",
        "ai": false,
        "note": "When something goes wrong, staff and members report it with a recording of the steps they took, so it gets fixed fast."
      },
      {
        "id": "F19",
        "name": "Staff phone push alerts for things needing action",
        "status": "Built",
        "ai": false,
        "note": "Staff get an alert on their phone the moment something needs them, with no separate app to install."
      },
      {
        "id": "F20",
        "name": "Arrival alert: staff are told when a member arrives (card scan at the door)",
        "status": "Built",
        "ai": false,
        "note": "Staff are told a member is arriving so they can greet them by name."
      },
      {
        "id": "F21",
        "name": "In-app guided help and step-by-step guides per role",
        "status": "Built",
        "ai": false,
        "note": "Each role gets step-by-step guides inside the app, so new staff learn on the job without training classes."
      },
      {
        "id": "X22",
        "name": "Defect monitoring across every club: failed actions, crashed screens and outages are caught automatically with a step recording, triaged by support, and each GM sees their own club's",
        "status": "Built",
        "ai": false,
        "note": "Problems are found before anyone calls: every failure at every club is captured with the steps that led to it, and support answers the club inside the app."
      },
      {
        "id": "X28",
        "name": "Chat on the club website and member app: the AI assistant answers first, hands off to a person on the team, or becomes a case; a visitor's chat becomes a lead",
        "status": "Built",
        "ai": true,
        "note": "A visitor asking about membership at 11pm gets an answer and lands in the pipeline as a lead; a member's question goes to a real person with photos and voice notes when the bot can't answer."
      },
      {
        "id": "X30",
        "name": "AI sorts every incoming inquiry by topic, and staff can see and correct each sort",
        "status": "Built",
        "ai": true,
        "note": "Wedding, membership and complaint messages arrive already sorted by topic, and the counts show how often staff had to correct it."
      },
      {
        "id": "C32",
        "name": "Work orders with request tracking (maintenance)",
        "status": "Built",
        "ai": false,
        "note": "Staff file Facilities and IT requests from My Requests; each becomes a tracked case on the club's queue that the asker follows."
      },
      {
        "id": "X13",
        "name": "Phone calling and texting with unknown-caller matching",
        "status": "Configure",
        "ai": false,
        "note": "Needs the club's calling-service account and its webhook."
      },
      {
        "id": "X31",
        "name": "Unified SMS: two-way texting with members through the club's own texting account, one conversation per person, STOP/START/HELP handled, delivery receipts, and texts from reminders and automations on the same thread",
        "status": "Configure",
        "ai": false,
        "note": "Built; needs the club's texting-provider account and its webhook."
      },
      {
        "id": "C31",
        "name": "NPS and sentiment surveys with industry benchmarking (AI sentiment)",
        "status": "Gap",
        "ai": false,
        "note": "NPS and OSAT surveys with scores by club and month are built, but there is no industry benchmarking and no AI sentiment on the answers."
      }
    ]
  },
  {
    "key": "member",
    "name": "Member App & Portal",
    "blurb": "What members do on their phones: book, pay, carry their card.",
    "features": [
      {
        "id": "F22",
        "name": "Installable member app (PWA/native) with digital member card / QR",
        "status": "Built",
        "ai": false,
        "note": "Members put the club app on their home screen and carry a member card with a QR code for each family member."
      },
      {
        "id": "F24",
        "name": "One household bookings list (all family members, all amenities)",
        "status": "Built",
        "ai": false,
        "note": "The whole family's tee times, classes, dinners and events show up in one list."
      },
      {
        "id": "F25",
        "name": "Book tee times, classes, sessions, dining and events from the app",
        "status": "Built",
        "ai": false,
        "note": "Members book golf, courts, classes, lessons, dinner and events from one app."
      },
      {
        "id": "F26",
        "name": "Booking confirmations with calendar (.ics) files and self-reschedule",
        "status": "Built",
        "ai": false,
        "note": "Every booking lands in the member's own calendar, and they can move it themselves without calling the desk."
      },
      {
        "id": "F27",
        "name": "Club wallet / member credit that pays anywhere (department-locked)",
        "status": "Built",
        "ai": false,
        "note": "Club credit can be locked to a department, like pro shop only, and is used first anywhere the member pays."
      },
      {
        "id": "F28",
        "name": "Pay Now, autopay, online statements",
        "status": "Built",
        "ai": false,
        "note": ""
      },
      {
        "id": "F29",
        "name": "Group scorecard / golf scoring in the app",
        "status": "Built",
        "ai": false,
        "note": "A whole group keeps score together on their phones during the round."
      },
      {
        "id": "F30",
        "name": "Multi-club reciprocity: see and book tee times at nearby clubs in the network",
        "status": "Built",
        "ai": false,
        "note": "A member traveling can see and book tee times at other clubs in the network nearby, priced and capped by their plan."
      },
      {
        "id": "F31",
        "name": "Guest passes bought at booking, guest fees",
        "status": "Built",
        "ai": false,
        "note": ""
      },
      {
        "id": "X04",
        "name": "Check-in desk and front desk scanning member QR cards with waiver and capacity checks",
        "status": "Built",
        "ai": false,
        "note": "The front desk sees the member's photo and status the instant their card is scanned."
      },
      {
        "id": "X06",
        "name": "Membership lifecycle actions: hold, resign with exit survey, transfer/sell, reinstate, move home club",
        "status": "Built",
        "ai": false,
        "note": "Resignations route for approval and trigger save calls before the member is gone."
      },
      {
        "id": "X08",
        "name": "Committees and ambassador programs",
        "status": "Built",
        "ai": false,
        "note": ""
      },
      {
        "id": "X20",
        "name": "Refer a Friend with a club-set wallet reward",
        "status": "Built",
        "ai": false,
        "note": "Members earn club credit for bringing in new members."
      },
      {
        "id": "X21",
        "name": "Push notifications to members' phones: booking confirmations, day-before reminders, statements and club announcements, with topic choices",
        "status": "Built",
        "ai": false,
        "note": "Members are asked for alerts right after they book, the moment they want a reminder, and every booking, statement and announcement reaches their phone."
      },
      {
        "id": "X35",
        "name": "A signed waiver on every booking, a parent signs for a child, and visitors wait behind members on a full class and pay when a place opens",
        "status": "Built",
        "ai": false,
        "note": ""
      },
      {
        "id": "X37",
        "name": "Self check-in at a check-in tablet: every class, program, event and court booking gets a one-time QR code in the email and the app, or scan the member card; a past-due balance, unpaid booking or unsigned waiver sends them to the desk, and no-shows are marked Absent",
        "status": "Built",
        "ai": false,
        "note": "Members check themselves in with the code from their confirmation email; the desk only hears about the ones who need help."
      },
      {
        "id": "C20",
        "name": "Member directory / roster in the app",
        "status": "Built",
        "ai": false,
        "note": "Opt-in member directory in the member app, gated by a club app key."
      },
      {
        "id": "F23",
        "name": "Apple / Google Wallet membership pass",
        "status": "Configure",
        "ai": false,
        "note": "Built, including updates pushed to a saved pass. Needs the club's Apple and Google Wallet issuer accounts."
      },
      {
        "id": "C18",
        "name": "Door and gate access from the member app or card (digital keys, RFID, visitor passes)",
        "status": "Gap",
        "ai": false,
        "note": "The member card barcode and Wallet pass are shown at the desk, but nothing opens doors or gates (no digital keys, RFID lock control or visitor passes)."
      },
      {
        "id": "C19",
        "name": "Location-aware push (beacons / geofences)",
        "status": "Gap",
        "ai": false,
        "note": "Arrival alerts are sent by booking time and location is read only when the member taps; there are no geofence or beacon-triggered pushes."
      },
      {
        "id": "C21",
        "name": "Member community feed in the app",
        "status": "Gap",
        "ai": false,
        "note": "No member community feed or social posts in the app."
      },
      {
        "id": "C22",
        "name": "Self-service kiosk for check-in and purchases",
        "status": "Gap",
        "ai": false,
        "note": "Check-in is a staff-run front-desk scanner today. Member self check-in on an iPad (a one-time code per booking, the member card also works) is being built."
      },
      {
        "id": "C23",
        "name": "App home screen set by membership type, modules the club turns on",
        "status": "Gap",
        "ai": false,
        "note": "Modules are switched on per club for staff, but the member app home is not set by membership type."
      },
      {
        "id": "C25",
        "name": "Childcare reservations in the app",
        "status": "Gap",
        "ai": false,
        "note": "Play Center shows a parent the live check-in timer, but there are no advance childcare reservations in the app."
      },
      {
        "id": "C26",
        "name": "Booking widget to embed on any existing website, and booking from search results",
        "status": "Gap",
        "ai": false,
        "note": "Only forms and chat can be embedded; there is no booking widget for an outside website and no booking from search results."
      }
    ]
  },
  {
    "key": "golf",
    "name": "Golf & Amenities",
    "blurb": "Tee sheet, rules per plan, carts, courts, classes and lessons.",
    "features": [
      {
        "id": "F32",
        "name": "Tee sheet with waitlist, standing tee times and weekend lottery",
        "status": "Built",
        "ai": false,
        "note": "The tee sheet runs waitlists, standing weekly times and a fair weekend lottery on its own."
      },
      {
        "id": "F33",
        "name": "Benefit/entitlement rules engine per plan (booking windows, caps, included vs. fee)",
        "status": "Built",
        "ai": false,
        "note": "One rules engine answers allow, warn or refuse with a reason for every booking, across every club and plan."
      },
      {
        "id": "F34",
        "name": "Turn stand ordering and weather on the tee sheet",
        "status": "Built",
        "ai": false,
        "note": "Golfers order food for the turn from the course, and the weather sits right on the tee sheet."
      },
      {
        "id": "F35",
        "name": "Rental fleet (carts) with inspections",
        "status": "Built",
        "ai": false,
        "note": "Every rental cart is inspected and tracked before and after it goes out."
      },
      {
        "id": "F36",
        "name": "Rain checks and no-show policy handling",
        "status": "Built",
        "ai": false,
        "note": "Rain checks are issued at the booking, and no-shows are handled by the club's own rule instead of a staff judgment call."
      },
      {
        "id": "F37",
        "name": "Agronomy / course maintenance log",
        "status": "Built",
        "ai": false,
        "note": "The superintendent's chemical log, chemical shed and turf weather live in the same system as the tee sheet."
      },
      {
        "id": "F39",
        "name": "Facility hours, courts and amenity scheduling",
        "status": "Built",
        "ai": false,
        "note": ""
      },
      {
        "id": "X03",
        "name": "Play Center (kids club) check-in with overtime charges",
        "status": "Built",
        "ai": false,
        "note": "Parents drop children off with a code, and late pick-ups are charged automatically."
      },
      {
        "id": "X10",
        "name": "Classes, programs, personal trainers and session packages",
        "status": "Built",
        "ai": false,
        "note": ""
      },
      {
        "id": "X11",
        "name": "Appointments with providers and lesson pros, with no-show fees",
        "status": "Built",
        "ai": false,
        "note": ""
      },
      {
        "id": "C03",
        "name": "Starter and ranger sheet on a tablet: start, turn and finish times, carts",
        "status": "Built",
        "ai": false,
        "note": "Starter, turn and ranger screens on the POS tablet or phone send groups off, record the turn and finish, and show carts per group."
      },
      {
        "id": "C04",
        "name": "Pace-of-play tracking",
        "status": "Built",
        "ai": false,
        "note": "Course Live and the ranger phone show each group's minutes behind and who is holding up whom, from the starter and turn timestamps."
      },
      {
        "id": "C05",
        "name": "Golf leagues and outings with automatic tee-sheet blocks and rotating nines",
        "status": "Built",
        "ai": false,
        "note": "Leagues are their own record (members, runs, rounds); each league places its blocks on the tee sheet on its own schedule, including rotating nines, and a league round fee is the club's own charge."
      },
      {
        "id": "C07",
        "name": "GPS rangefinder and scorecard app",
        "status": "Built",
        "ai": false,
        "note": "The member app shows each hole drawn from the course map with Front, Center and Back yards from the golfer's own location (or from their own tee), hazards ahead and the wind, plus the group scorecard with games."
      },
      {
        "id": "C12",
        "name": "Punch cards and one-time vouchers usable across courses, scanned on the tee sheet",
        "status": "Built",
        "ai": false,
        "note": "Punch cards and one-time vouchers are sold at the desk or bought by members in the app (wallet or card), scanned on the tee sheet, topped up, and refunded for unused punches; sales are held as Unearned Punch Cards until used."
      },
      {
        "id": "C16",
        "name": "Tee-time reminders the golfer confirms or changes",
        "status": "Built",
        "ai": false,
        "note": "Tee-time reminders go out by email (and text where opted in) with Confirm and Cancel links, and the member can reschedule from My Golf."
      },
      {
        "id": "F38",
        "name": "Handicap and tournament system connections",
        "status": "Configure",
        "ai": false,
        "note": "Needs the club's handicap-service connection and tournament-system key."
      },
      {
        "id": "X32",
        "name": "Course map for every course from open map data, with points the club places on a phone; live cart tracking with alerts for behind pace, no signal and left the property; path-only and closed holes with dates",
        "status": "Configure",
        "ai": false,
        "note": "Built; live cart positions need trackers or phones in the carts."
      },
      {
        "id": "C09",
        "name": "Caddie management: availability, member requests, assignment, texting caddies",
        "status": "Configure",
        "ai": false,
        "note": "Caddies set their availability, members ask for a caddie when booking, and the caddie board assigns caddies to the groups that asked; the member sees what was arranged. Texting caddies needs the club's texting number."
      },
      {
        "id": "C06",
        "name": "Live tournament leaderboards on TV screens, and tournament sync to tee times",
        "status": "Gap",
        "ai": false,
        "note": "Tournament results come back from the tournament system, but there is no TV leaderboard screen and no sync to tee times."
      },
      {
        "id": "C08",
        "name": "Driving range ball-machine connection",
        "status": "Gap",
        "ai": false,
        "note": "No driving-range ball machine integration; range balls are only a counter product."
      },
      {
        "id": "C10",
        "name": "Spa management: treatments, providers, health notes, add-ons, commissions",
        "status": "Gap",
        "ai": false,
        "note": "Appointments with providers exist and spa charges from the hotel system post in, but there is no treatment menu, health notes, add-ons or spa commissions."
      },
      {
        "id": "C11",
        "name": "Marina management: slips, storage, transient reservations",
        "status": "Gap",
        "ai": false,
        "note": "No marina module: no slips, boat storage or transient slip reservations."
      },
      {
        "id": "C13",
        "name": "Bot protection for online tee-time booking (one-time booking code)",
        "status": "Gap",
        "ai": false,
        "note": "Online tee-time booking has no bot protection such as a one-time booking code or CAPTCHA."
      },
      {
        "id": "C14",
        "name": "Sunrise/sunset-aligned tee sheet and split-tee / back-nine starts",
        "status": "Gap",
        "ai": false,
        "note": "Sunrise and sunset are computed only for the weather strip and a starting hole can be set per booking; the sheet is not built from sunrise/sunset and there is no split-tee (1st and 10th) sheet."
      },
      {
        "id": "C15",
        "name": "Agronomy sensors (soil moisture mapping)",
        "status": "Gap",
        "ai": false,
        "note": "There is a manual agronomy log only; no soil moisture or other sensor feed."
      },
      {
        "id": "IC53",
        "name": "Racquet leagues, ladders and round robins",
        "status": "Gap",
        "ai": false,
        "note": "Not built yet."
      },
      {
        "id": "IC55",
        "name": "Swim levels, progression and swim meets",
        "status": "Gap",
        "ai": false,
        "note": "Not built yet."
      }
    ]
  },
  {
    "key": "pos",
    "name": "POS & Dining",
    "blurb": "Registers, dining reservations, menus and stock.",
    "features": [
      {
        "id": "F40",
        "name": "iPad POS for pro shop and restaurant, member charging",
        "status": "Built",
        "ai": false,
        "note": "An iPad register for the pro shop and the dining room charges straight to the member's account with credit and limits checked."
      },
      {
        "id": "F41",
        "name": "Register clock-in by face; member card scan pays",
        "status": "Built",
        "ai": true,
        "note": "Staff clock in at the register with their face, and a member's card scan pays for their items."
      },
      {
        "id": "F42",
        "name": "Dining reservations, host stand, dining minimums per plan",
        "status": "Built",
        "ai": false,
        "note": "The host stand sees every room's floor plan and tracks each member's dining minimum as they spend."
      },
      {
        "id": "F43",
        "name": "Menu with dish photos, diet tags, sides and pairings",
        "status": "Built",
        "ai": false,
        "note": "Servers see a photo of each dish, its diet tags and what to pair it with right on the menu."
      },
      {
        "id": "F44",
        "name": "Inventory: stock ledger, special orders, FIFO/LIFO cost, profit by item",
        "status": "Built",
        "ai": false,
        "note": "Stock on hand comes from one movement ledger with true FIFO or LIFO cost, so profit by item is real."
      },
      {
        "id": "F45",
        "name": "Staff pay from POS: tips, commission, caddie loops",
        "status": "Built",
        "ai": false,
        "note": "Tips, commissions and caddie loops are counted from the register and go straight to payroll."
      },
      {
        "id": "F46",
        "name": "Promo codes and member discounts at the register",
        "status": "Built",
        "ai": false,
        "note": ""
      },
      {
        "id": "X09",
        "name": "Carry-out online ordering to the kitchen screen",
        "status": "Built",
        "ai": false,
        "note": "Members order carry-out from the app and it prints straight to the kitchen."
      },
      {
        "id": "X39",
        "name": "Pro shop orders picked up item by item: mark 2 of 3 shirts picked up today and the last one tomorrow, who took each and when, and the order closes itself when the last item goes",
        "status": "Built",
        "ai": false,
        "note": "The member who picks up half an order today is never told the whole order is gone."
      },
      {
        "id": "C34",
        "name": "Kitchen display system with station routing and seat-level tickets",
        "status": "Built",
        "ai": false,
        "note": "Kitchen and bar screens with items routed by station, course hold and fire, seat numbers and seat allergies on each ticket, and optional ticket printers (two stations, kitchen and bar)."
      },
      {
        "id": "C35",
        "name": "Offline mode for the mobile POS",
        "status": "Built",
        "ai": false,
        "note": "The dining POS keeps taking cash and house-account sales offline and replays them when the connection returns; cards are refused offline."
      },
      {
        "id": "C36",
        "name": "Round-up-to-charity at the register",
        "status": "Built",
        "ai": false,
        "note": "Round up for charity at the register, with the club's chosen fund and its own charge code."
      },
      {
        "id": "C37",
        "name": "Pro shop online store synced with POS stock",
        "status": "Built",
        "ai": false,
        "note": "The member web shop sells from the same pro shop catalog and stock ledger the POS register uses."
      },
      {
        "id": "X33",
        "name": "Order food and drinks from the course: the beverage cart brings it to your hole or cart, or pick it up at the turn; pay by wallet, house account or card; an ID check for drinks with alcohol; the cart attendant's phone shows orders on the map",
        "status": "Configure",
        "ai": false,
        "note": "Built; the online ID check needs the club's identity-check account."
      },
      {
        "id": "X34",
        "name": "Card readers paired to registers, with the credit card fee shown before the member pays",
        "status": "Configure",
        "ai": false,
        "note": "Built; needs the club's card readers and card processing account."
      },
      {
        "id": "X38",
        "name": "21+ age check by photo: the member photographs their ID and a selfie, the club's own AI model reads the name, date of birth and expiration, a staff member confirms once, and the photos are deleted",
        "status": "Configure",
        "ai": true,
        "note": ""
      }
    ]
  },
  {
    "key": "events",
    "name": "Events & Catering",
    "blurb": "From the first quote to the event-day captain and the close-out.",
    "features": [
      {
        "id": "F47",
        "name": "Event planning: BEO, rooms, layouts, decor, catering menus, price book",
        "status": "Built",
        "ai": false,
        "note": "One room rule stops two events from ever being booked into the same room, and the BEO, layout and menu sit on the same event."
      },
      {
        "id": "F48",
        "name": "Event staffing, inventory, food purchasing, vendors",
        "status": "Built",
        "ai": false,
        "note": "Staffing, rentals, food ordering and vendors for an event are planned in the same place as the event."
      },
      {
        "id": "F49",
        "name": "Guest lists, RSVP and seating charts",
        "status": "Built",
        "ai": false,
        "note": "Guests RSVP online and the seating chart is built from the same guest list."
      },
      {
        "id": "F50",
        "name": "Event-day captain app",
        "status": "Built",
        "ai": false,
        "note": "The event captain runs the night from a phone screen with the timeline, the guests and day-of charges."
      },
      {
        "id": "F51",
        "name": "Event close-out and event reports",
        "status": "Built",
        "ai": false,
        "note": ""
      },
      {
        "id": "X25",
        "name": "Booked-but-unpaid events get one reminder, then release automatically; the GM and events team are told",
        "status": "Built",
        "ai": false,
        "note": "Rooms are never held for a party that never pays: one polite reminder, then the date is released and the team is told, without anyone chasing it."
      },
      {
        "id": "X26",
        "name": "One event catalog for every club: packages, dishes and services written once, offered at every club or chosen ones, each club free to keep its own version and price",
        "status": "Built",
        "ai": false,
        "note": "Corporate writes the wedding package once and every club sells it the same day; a club can still tweak its own version and price, and anything missing a required detail can't be sold."
      },
      {
        "id": "X45",
        "name": "A new vendor is asked for their W-9 and insurance in one step, and damage at an event is billed to the client, taxed by the club's state and booked to damage recovery",
        "status": "Built",
        "ai": false,
        "note": ""
      },
      {
        "id": "C38",
        "name": "Rooms split into sub-rooms, with set-up and tear-down time blocked",
        "status": "Built",
        "ai": false,
        "note": "Combined rooms are built from component rooms, and room availability blocks each event's setup and teardown minutes."
      }
    ]
  },
  {
    "key": "finance",
    "name": "Billing & Accounting",
    "blurb": "Dues, statements, refunds and each club's own books.",
    "features": [
      {
        "id": "F52",
        "name": "Dues engine and member billing with dunning",
        "status": "Built",
        "ai": false,
        "note": "Dues are billed by the club's own engine, retried automatically, and charging is paused when an account falls behind."
      },
      {
        "id": "F53",
        "name": "Full general ledger / accounting per club (AR, AP, GL, statements)",
        "status": "Built",
        "ai": false,
        "note": "Every club has its own complete books, and every sale, booking and payroll run posts to them automatically."
      },
      {
        "id": "F55",
        "name": "Corporate treasury: debt, leases, inter-entity",
        "status": "Built",
        "ai": false,
        "note": "Corporate finance gets loans, leases and inter-club accounting in the same books as the clubs."
      },
      {
        "id": "F56",
        "name": "Fixed asset register (incl. fleet)",
        "status": "Built",
        "ai": true,
        "note": "Carts, mowers and kitchen equipment sit on one asset register that depreciates into the club's own books."
      },
      {
        "id": "F57",
        "name": "Refunds: split payment, card refund on cancel, shop returns",
        "status": "Built",
        "ai": false,
        "note": ""
      },
      {
        "id": "F58",
        "name": "Card surcharge by card brand",
        "status": "Built",
        "ai": false,
        "note": "The card fee is set per card brand, so the club recovers what each card actually costs."
      },
      {
        "id": "F59",
        "name": "Data feeds out with retries",
        "status": "Built",
        "ai": false,
        "note": "Ledger and member data go to the club's reporting warehouse on a schedule, with retries if a send fails."
      },
      {
        "id": "X02",
        "name": "Gift cards sold and redeemed at the club",
        "status": "Built",
        "ai": false,
        "note": ""
      },
      {
        "id": "X17",
        "name": "Purchasing with approval limits, purchase orders and three-way match; 13-week cash forecast",
        "status": "Built",
        "ai": false,
        "note": "Purchase orders are matched against receipts and invoices before anything is paid."
      },
      {
        "id": "X40",
        "name": "The credit card fee on every card charge where the state allows it, at the card brand's rate, with the fee's own sales tax, shown before the member pays; debit never pays it, returns and refunds give back its share, and a donation's fee is never counted as the gift",
        "status": "Built",
        "ai": false,
        "note": "One rule on every till, screen and bill, so the club never quietly absorbs card costs."
      },
      {
        "id": "X41",
        "name": "Our own subscription billing for every membership: the club's dues run bills each period on the club's draft day, plan changes and cancellations are handled in-house, and the card processor only charges the card on file, so no membership depends on a processor's subscription system",
        "status": "Built",
        "ai": false,
        "note": "Switching card processors never touches a single member's billing schedule."
      },
      {
        "id": "X42",
        "name": "Every club's card processor known to the books: its deposits are entered as settlements with their fees, every payment names the processor that took it, and each club is reconciled against its own processor and its bank",
        "status": "Built",
        "ai": false,
        "note": "The controller sees, club by club, that what the processor deposited is what the members paid, less fees."
      },
      {
        "id": "X43",
        "name": "Every cent has a department: each income, cost and expense line names its department or waits on a short list for the controller; drawer pay-outs post to their own accounts; a deleted or recycled record takes its postings back, and a restore posts them again",
        "status": "Built",
        "ai": false,
        "note": "No floating charge: every dollar on the P&L sits with a department, so each manager owns their numbers."
      },
      {
        "id": "X44",
        "name": "Past-due dues follow-up: when card retries run out, the GM (or the Membership Director) gets a next step and a phone alert; turning autopay off needs a reason; collecting a payment is its own permission",
        "status": "Built",
        "ai": false,
        "note": "A failed draft never goes quiet: someone is named to follow it up the day the retries end."
      },
      {
        "id": "C39",
        "name": "Prepaid tee-time and event deposits held as a liability until used",
        "status": "Built",
        "ai": false,
        "note": "Prepaid tee times are held as a liability until the round is played, alongside event deposits."
      },
      {
        "id": "F54",
        "name": "Statement runs with PDF and print files",
        "status": "Configure",
        "ai": false,
        "note": "Statement PDFs and the generic print file work. Lanvera's own file layout follows their specification and SFTP account."
      },
      {
        "id": "X12",
        "name": "Hotel room charges posted to the member's house account",
        "status": "Configure",
        "ai": false,
        "note": "Needs the hotel system account and which room charges go to the house account."
      },
      {
        "id": "C40",
        "name": "Declined-payment recovery: retry timing, card updater",
        "status": "Configure",
        "ai": false,
        "note": "Declined dues are retried on a schedule with card-expiry warnings; card updating relies on the payment processor."
      },
      {
        "id": "C42",
        "name": "Financial benchmarking against other clubs from the trial balance",
        "status": "Gap",
        "ai": false,
        "note": "Clubs in the same group compare sales figures; there is no financial benchmarking against other operators."
      },
      {
        "id": "C43",
        "name": "Built-in payment processing with tipping on the device",
        "status": "Gap",
        "ai": false,
        "note": "Keyed cards and tip buttons work, but there is no integrated card reader; card-present sales use a standalone terminal."
      }
    ]
  },
  {
    "key": "people",
    "name": "HR, Payroll & Staff",
    "blurb": "Hiring, shifts, time off, the time clock and payroll.",
    "features": [
      {
        "id": "F60",
        "name": "HR and payroll with payroll-provider export, every money event posted to the ledger",
        "status": "Built",
        "ai": false,
        "note": "Every payroll dollar posts to the books on its own, and the payroll provider's file is ready each pay period."
      },
      {
        "id": "F61",
        "name": "Hiring with AI candidate matching",
        "status": "Built",
        "ai": true,
        "note": "AI ranks applicants against the job so managers interview the best fits first."
      },
      {
        "id": "F62",
        "name": "Shifts by location and \"My Week\" staff schedule",
        "status": "Built",
        "ai": false,
        "note": ""
      },
      {
        "id": "F63",
        "name": "Face sign-in with liveness",
        "status": "Built",
        "ai": true,
        "note": "Face sign-in checks that a live person is there, so no one can clock in a coworker with a photo."
      },
      {
        "id": "F64",
        "name": "Time off requests and adjustments",
        "status": "Built",
        "ai": false,
        "note": ""
      },
      {
        "id": "X16",
        "name": "Team Chat with department channels and a staff phone app (updates, newsletter, pay, hours)",
        "status": "Built",
        "ai": false,
        "note": "Staff have their own phone app for schedule, pay, time off and club news."
      },
      {
        "id": "C44",
        "name": "Instructor substitutes, cost per head, payroll vs. teaching-time variance",
        "status": "Gap",
        "ai": false,
        "note": "No instructor substitutes, cost per head or payroll-versus-teaching-time variance for classes."
      },
      {
        "id": "C45",
        "name": "Staff app: broadcasts, member lookups, rule citations",
        "status": "Gap",
        "ai": false,
        "note": "The staff phone app has team messages, broadcasts and member lookup (with fields hidden by permission), but no rule citations."
      }
    ]
  },
  {
    "key": "platform",
    "name": "Platform, Security & AI",
    "blurb": "Many clubs, permissions, audit, reporting and the AI helpers.",
    "features": [
      {
        "id": "F65",
        "name": "Many clubs in one system, with one club switcher that scopes every screen",
        "status": "Built",
        "ai": false,
        "note": "One club picker narrows every screen to a club, and the corporate view rolls every club up side by side."
      },
      {
        "id": "F66",
        "name": "Object permissions and a role hierarchy, with row-level security",
        "status": "Built",
        "ai": false,
        "note": "Who sees what is set by job, sharing and hierarchy, and the database itself enforces it."
      },
      {
        "id": "F67",
        "name": "\"See their portal\" / \"Log in as\" member for support",
        "status": "Built",
        "ai": false,
        "note": "Support staff see exactly what a member sees, read-only, to answer questions on the phone."
      },
      {
        "id": "F68",
        "name": "Person merge with a preview",
        "status": "Built",
        "ai": false,
        "note": "Merging two duplicate people shows a full preview of the result before anything changes."
      },
      {
        "id": "F69",
        "name": "Required fields and validation rules screen (no code)",
        "status": "Built",
        "ai": false,
        "note": "Admins set required fields and rules on a screen, with no developer needed."
      },
      {
        "id": "F70",
        "name": "The club's own AI model: reads floor plans, receipts and asset labels",
        "status": "Built",
        "ai": true,
        "note": "AI reads a floor plan photo into a room layout and a receipt photo into an expense."
      },
      {
        "id": "F71",
        "name": "Audit log and one timeline per record",
        "status": "Built",
        "ai": false,
        "note": ""
      },
      {
        "id": "F72",
        "name": "Executive dashboards and reporting across clubs",
        "status": "Built",
        "ai": false,
        "note": "Executives see every club's numbers side by side without exporting to a separate reporting tool."
      },
      {
        "id": "X15",
        "name": "Report builder with datasets, dashboards and scheduled emailed reports",
        "status": "Built",
        "ai": false,
        "note": "Managers build their own reports and get them by email on a schedule, limited to what they may see."
      },
      {
        "id": "X18",
        "name": "AI helper for staff: ask any question about the club in plain English and get the answer with the reports it came from, limited to what that person may see",
        "status": "Built",
        "ai": true,
        "note": "\"How many juniors joined this quarter?\" gets a cited answer in seconds, and it never shows anyone a number their permissions hide."
      },
      {
        "id": "X19",
        "name": "Approvals routed up the role hierarchy",
        "status": "Built",
        "ai": false,
        "note": "Approvals go to the right person by the role hierarchy, so nothing waits on someone who isn't in charge of it."
      },
      {
        "id": "X23",
        "name": "Every upload checked for disguised files, and logs forwarded with personal details masked",
        "status": "Built",
        "ai": false,
        "note": "A renamed or disguised file is refused at upload, and support logs never carry a member's personal details."
      },
      {
        "id": "X24",
        "name": "Permission explainer: for any staff member, what they can do club by club and why (role, extra grant or removal), in plain words for every permission",
        "status": "Built",
        "ai": false,
        "note": "Ask \"why can't Sam refund this?\" and the screen answers in a sentence: which role or grant gives or takes away that permission, at which club."
      },
      {
        "id": "X29",
        "name": "Guided workflows for every process: Walk Me Through It puts the steps beside the real work on each record, checks each step's rules, and admins edit the steps with versions and restore",
        "status": "Built",
        "ai": false,
        "note": "A new hire can sell a membership or plan a wedding on day one: the record shows the next step, refuses one that isn't ready, and asks for anything missing in place."
      },
      {
        "id": "X36",
        "name": "Every edit is audited: who changed what, when, and the value before, on every record",
        "status": "Built",
        "ai": false,
        "note": ""
      },
      {
        "id": "C47",
        "name": "Predictive member analytics (churn risk)",
        "status": "Built",
        "ai": false,
        "note": "Every member gets a nightly churn-risk score and reasons from visits, app sign-ins, tenure and billing, with retention calls logged; it is rule-based, not a model."
      },
      {
        "id": "X14",
        "name": "Sign in with the club's Microsoft accounts, groups mapped to jobs",
        "status": "Configure",
        "ai": false,
        "note": "Needs the club's Microsoft app registration, admin consent and the group-to-job list."
      },
      {
        "id": "C46",
        "name": "Document repository linked to members, vendors and employees",
        "status": "Gap",
        "ai": false,
        "note": "Vendors and staff have document stores, but member records hold only signed contracts; there is no general document repository with uploads for members."
      },
      {
        "id": "C48",
        "name": "Gatehouse, visitor and vendor management (POA/HOA)",
        "status": "Gap",
        "ai": false,
        "note": "No gatehouse, visitor or vendor gate management."
      }
    ]
  }
];
